---
- hosts: all
  become: yes
# become_user: root
# become_method: su
  tasks:
    - name: install httpd
      yum: name=httpd state=latest

- name: ensure apache is running
    service:
        name: httpd
        state: started
